version: "3.5"
services:
  pearshop_db:
    build: sql
    image: pearshop-mariadb:10.6.5-focal
    container_name: pearshop_db
    ports:
      - 8888:3306
    environment:
      MYSQL_ROOT_PASSWORD: donotusethisinphpcode!
      MYSQL_DATABASE: pearstore_database
      MYSQL_USER: pearshop
      MYSQL_PASSWORD: itsstuttgart
  pearshop_www:
    build: www
    image: pearshop-php:8.1.3-apache
    container_name: pearshop_www
    ports:
      - 8080:80
    depends_on:
      - pearshop_db