FROM php:8.1.3-apache

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli && a2enmod rewrite
RUN apt-get update && apt-get upgrade -y

RUN a2enmod rewrite

# rewrite_module enable

# And clean up the image
RUN rm -rf /var/lib/apt/lists/*
